suppress-self-cert-warning: true
auto-copy-stagers: true
mouse-support: false
servers:
  localhost:
    host: http://localhost
    port: 1337
    socketport: 5000
    username: empireadmin
    password: password123
    autoconnect: true
  other-server:
    host: http://localhost
    port: 1337
    socketport: 5000
    username: empireadmin
    password: password123
  another-one:
    host: http://localhost
    port: 1337
    socketport: 5000
    username: empireadmin
    password: password123
shortcuts:
  # Params can be a list like
  # params:
  #   - name: ratio
  #     value: 80
  #   - name: location
  #     value: /tmp
  #   - name: listener
  #     dynamic: true
  # If a value is provided, it is static values.
  # If dynamic is set to true, then you will provide the parameter
  # when calling the shortcut in the order they appear like 'sc http1'
  # Because order matters, we use a sequence instead of a map
  powershell:
    whoami:
      shell: whoami
    ps:
      shell: ps
    sc:
      module: powershell_collection_screenshot
      params:
        - name: Ratio
          value: 80
    keylog:
      module: powershell_collection_keylogger
      params:
        - name: Sleep
          value: 0
    sherlock:
      module: powershell_privesc_sherlock
    mimikatz:
      module: powershell_credentials_mimikatz_logonpasswords
    psinject:
      module: powershell_management_psinject
      params:
        - name: Listener
          dynamic: true
        - name: ProcId
          dynamic: true
    revtoself:
      module: powershell_credentials_tokens
      params:
        - name: RevToSelf
          value: true
    shinject:
      module: powershell_management_shinject
      params:
        - name: Listener
          dynamic: true
        - name: ProcId
          dynamic: true
    spawn:
      module: powershell_management_spawn
      params:
        - name: Listener
          dynamic: true
    steal_token:
      module: powershell_credentials_tokens
      params:
        - name: ImpersonateUser
          value: true
        - name: ProcessID
          dynamic: true
    bypassuac:
      module: powershell_privesc_bypassuac_eventvwr
      params:
        - name: Listener
          dynamic: true
    bof:
      module: csharp_inject_bof_inject_bof
      params:
        - name: Architecture
          value: x64
        - name: File
          dynamic: true
    assembly:
      module: csharp_assembly.Assembly
      params:
        - name: File
          dynamic: true
        - name: Parameters
          value: ''
  python:
    whoami:
      shell: whoami
    ps:
      shell: ps
    sc:
      module: python_collection_osx_screenshot
      params:
        - name: SavePath
          dynamic: true
    keylog:
      module: python_collection_osx_keylogger
      params:
        - name: LogFile
          dynamic: true
  ironpython:
    whoami:
      shell: whoami
    ps:
      shell: ps
    sc:
      module: powershell_collection_screenshot
      params:
        - name: Ratio
          value: 80
    keylog:
      module: powershell_collection_keylogger
      params:
        - name: Sleep
          value: 0
    sherlock:
      module: powershell_privesc_sherlock
    mimikatz:
      module: powershell_credentials_mimikatz_logonpasswords
    psinject:
      module: powershell_management_psinject
      params:
        - name: Listener
          dynamic: true
        - name: ProcId
          dynamic: true
    revtoself:
      module: powershell_credentials_tokens
      params:
        - name: RevToSelf
          value: true
    shinject:
      module: powershell_management_shinject
      params:
        - name: Listener
          dynamic: true
        - name: ProcId
          dynamic: true
    spawn:
      module: powershell_management_spawn
      params:
        - name: Listener
          dynamic: true
    steal_token:
      module: powershell_credentials_tokens
      params:
        - name: ImpersonateUser
          value: true
        - name: ProcessID
          dynamic: true
    bypassuac:
      module: powershell_privesc_bypassuac_eventvwr
      params:
        - name: Listener
          dynamic: true
    bof:
      module: csharp_inject_bof_inject_bof
      params:
        - name: Architecture
          value: x64
        - name: File
          dynamic: true
    assembly:
      module: csharp_assembly.Assembly
      params:
        - name: File
          dynamic: true
        - name: Parameters
          value: ''
  csharp:
    whoami:
      shell: whoami
    ps:
      shell: ps
    sc:
      module: powershell_collection_screenshot
      params:
        - name: Ratio
          value: 80
    keylog:
      module: powershell_collection_keylogger
      params:
        - name: Sleep
          value: 0
    sherlock:
      module: powershell_privesc_sherlock
    mimikatz:
      module: powershell_credentials_mimikatz_logonpasswords
    psinject:
      module: powershell_management_psinject
      params:
        - name: Listener
          dynamic: true
        - name: ProcId
          dynamic: true
    revtoself:
      module: powershell_credentials_tokens
      params:
        - name: RevToSelf
          value: true
    shinject:
      module: powershell_management_shinject
      params:
        - name: Listener
          dynamic: true
        - name: ProcId
          dynamic: true
    spawn:
      module: powershell_management_spawn
      params:
        - name: Listener
          dynamic: true
    steal_token:
      module: powershell_credentials_tokens
      params:
        - name: ImpersonateUser
          value: true
        - name: ProcessID
          dynamic: true
    bypassuac:
      module: powershell_privesc_bypassuac_eventvwr
      params:
        - name: Listener
          dynamic: true
    bof:
      module: csharp_inject_bof_inject_bof
      params:
        - name: Architecture
          value: x64
        - name: File
          dynamic: true
    assembly:
      module: csharp_assembly.Assembly
      params:
        - name: File
          dynamic: true
        - name: Parameters
          value: ''
directories:
  downloads: empire/client/downloads/
  generated-stagers: empire/client/generated-stagers/
tables:
  borders: true
logging:
  level: INFO
  directory: empire/client/downloads/logs/