name: Private - Tag Release
on:
  pull_request:
    types:
      - closed
    branches:
      - private-main

jobs:
  tag_release:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.repository == 'BC-Security/Empire-Sponsors' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Setup poetry
        run: |
          curl -sL https://install.python-poetry.org | python - -y
      - name: Set application version as variable
        run: |
          echo "APP_VERSION=$(poetry version -s)" >> $GITHUB_ENV
      - name: Extract release notes
        id: extract_release_notes
        uses: vinnybod/extract-release-notes@v2
      - name: Create Release Private
        id: create_release
        uses: actions/create-release@v1
        env:
          # Uses the non-default token in order to trigger other workflows.
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: v${{ env.APP_VERSION }}-private
          release_name: v${{ env.APP_VERSION }}-private
          body: ${{ steps.extract_release_notes.outputs.release_notes }}
          draft: false
          prerelease: false
